use_frameworks!

target 'VascTracX' do
  pod 'CardinalKit', :path => '../'
  pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :commit => '90c68d0d195f23fff1f618a9a4ffa518be9ac845'
  pod 'Granola', :git => 'https://github.com/CardinalKit/Granola.git', :branch => 'main'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'TinyConstraints'
  pod 'ChartView'
  pod 'FLCharts'

end